"""This file conatins all the constants required for training pipeline"""
Training_Data_Path="train.csv"
Test_Data_Path="test.csv"
Artifact_File_Path:str="Artifacts"
Dataset_Path="phishing.csv"
Data_Ingested="Ingested"